# Generated by Django 6.1 on 2026-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('junior-high', 'Junior High School'), ('senior-high', 'Senior High School'), ('undergraduate', 'Undergraduate')], max_length=30)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('activities', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('school_image', models.URLField(blank=True, null=True)),
                ('school_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
